xdg-desktop-portal: Add missing gobject-introspection
This is needed to find GLib typelib:
ImportError: cannot import name GLib, introspection typelib not found